### ISSUE TITLE
File Links are deprecated

### ISSUE THREAD

**Issue by mbu93** [impegoraro/sailfish-sgs3#1]
Hey!
I was running into Sailfish Os a few days ago and want to test it on my Galaxy S3, since it is the only device for testing purpose i've got. Sadly your file links are down. Is there a way to re-upload the content and refresh the links?
thanks in advance

**Comment by impegoraro** [comment]
Hey, sorry for the delayed response. Let me see if i can get the files uploaded again.

**Comment by mbu93** [comment]
Any update on this?

**Comment by mentalko** [comment]
@impegoraro Hello, i need this ROM too.

**Comment by Russanandres** [comment]
Hi. There is still no links on xda or website to rom. Does anyone still have it?
